/******************************************************************************
 * THIS FILE WAS GENERATED BY PFC, THE PIFFLE COMPILER
 * Command line arguments were: pcap_tcp.pfl 
 ******************************************************************************/
#line 4 "pcap_tcp.c"

int32_t ethertype(uint8_t inp[65536], uint32_t inp_sz)
{
    if (inp_sz < 16) {
        return -1;
    } else {
        return (int32_t) (((uint16_t) (inp[14]) << 8) | (uint16_t) (inp[15]));
    }
}

int ip_p(uint8_t inp[65536], uint32_t inp_sz)
{
    int32_t ethertype_s;
    
    ethertype_s = ethertype(inp, inp_sz);
    if (ethertype_s < 0) {
        return 0;
    } else {
        return ethertype_s == 2048;
    }
}

int32_t ip_protocol(uint8_t inp[65536], uint32_t inp_sz)
{
    if (inp_sz < 26) {
        return -1;
    } else {
        return (int32_t) (inp[25]);
    }
}

int tcp_p(uint8_t inp[65536], uint32_t inp_sz)
{
    int32_t ip_protocol_s;
    
    ip_protocol_s = ip_protocol(inp, inp_sz);
    if (ip_protocol_s < 0) {
        return 0;
    } else {
        return ip_protocol_s == 6;
    }
}

int udp_p(uint8_t inp[65536], uint32_t inp_sz)
{
    int32_t ip_protocol_s;
    
    ip_protocol_s = ip_protocol(inp, inp_sz);
    if (ip_protocol_s < 0) {
        return 0;
    } else {
        return ip_protocol_s == 17;
    }
}

uint32_t filter(uint8_t inp[65536], uint32_t inp_sz, uint8_t out[65536], 
                uint32_t out_sz)
{
    uint32_t out_sz_new;
    
    out_sz_new = ((inp_sz < out_sz) ? inp_sz : out_sz);
    {
        uint32_t i;
        
        for (i = 0; (i <= 65536) && (i < out_sz_new); i++) {
            out[i] = inp[i];
        }
    }
    if (!ip_p(inp, inp_sz)) {
        out_sz_new = 0;
    } 
    if (!tcp_p(inp, inp_sz)) {
        out_sz_new = 0;
    } 
    return out_sz_new;
}
